---
- name: Shows local defined vCenter definitions
  hosts: localhost

  tasks:
    - name: Ensure temp dir is there
      file:
        path: "{{ pors_temp_dir }}"
        state: directory

    - name: Clear/Prepare vCenters temp file
      copy:
        content: ""
        dest: "{{ pors_temp_dir }}/vcenters.list"

    - name: Collecting defined vCenters (sorted by occurence)
      lineinfile:
        line: "{{ item }}"
        path: "{{ pors_temp_dir }}/vcenters.list"
      with_items: "{{ vsphere.host }}"

