---
#####################################################################################################################
# Configurations for Splunk server.conf
####################################################################################################################

splunk_server_conf:
  clustering:
    mode: master
    pass4SymmKey: "{{ vault_clustering_pass4SymmKey }}"
  general:
    pass4SymmKey: "{{ vault_general_pass4SymmKey }}"
  sslConfig:
    sslPassword: "{{ vault_sslConfig_sslPassword }}"
  license:
    master_uri: dynamic
  indexer_discovery:
    pass4SymmKey: "{{ vault_indexerdiscovery_pass4SymmKey }}"
