---
- debug:
    var: target

- include: get_peernode_sites.yml
  when: target == "peernode"

- include: get_deployer_sites.yml
  when: target == "deployer"

- include: get_shcmember_sites.yml
  when: target == "shcmember"

- debug:
    var: parsed_groups
  when: parsed_groups is defined
