---
- name: Partitioning {{ server_disk_dev }}
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  parted:
    device: "{{ server_disk_dev }}"
    number: 1
    label: gpt
    state: present
  when: server_disk_dev is defined

- name: Make {{ server_disk_dev }} a swap device
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  shell: "mkswap {{ server_disk_dev }}1"
  when: server_disk_dev is defined

- name: add {{ server_disk_dev }} to fstab
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  mount:
    src: "{{ server_disk_dev }}"
    path: none
    opts: "{{ server_disk_mountopts | default('sw')}}"
    fstype: swap
    passno: "0"
    backup: yes
    state: present
  when: server_disk_dev is defined

- name: Enable the new swap space
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  shell: swapon -a
