---
- name: partitioning {{ server_disk_dev }}
  parted: 
    device: "{{ server_disk_dev }}" 
    number: 1
    label: gpt
    state: present
  when: server_disk_dev is defined 

- name: format {{ server_disk_dev }} with {{ server_disk_fs }}
  filesystem:
    fstype: "{{ server_disk_fs }}"
    dev: "{{ server_disk_dev }}1"
  when: server_disk_dev is defined

- name: add {{ server_disk_dev }} to fstab
  mount:
    src: "{{ server_disk_dev }}1"
    path: "{{ server_disk_mountpoint }}"
    opts: "{{ server_disk_mountopts | default('defaults', true)}}"
    fstype: "{{ server_disk_fs }}"
    passno: "0"
    backup: yes
    state: present
  when: server_disk_dev is defined

- name: create mountpoint {{ server_disk_mountpoint }} 
  file:
    path: "{{ server_disk_mountpoint }}"
    mode: '0755'
    state: directory
  when: server_disk_dev is defined and server_disk_mountpoint != "none"
