---
- name: Create temp mount {{ server_tmp_mnt }}
  file:
    path: "{{ server_tmp_mnt }}"
    state: directory

- name: Mount new disk {{ server_disk_dev }} to temp mount {{ server_tmp_mnt }}
  mount:
    src: "{{ server_disk_dev }}1"
    path: "{{ server_tmp_mnt }}"
    fstype: "{{ server_disk_fs }}"
    state: mounted

- name: Copy content of {{ server_disk_mountpoint }} to {{ server_tmp_mnt }}
  synchronize:
    src: "{{ server_disk_mountpoint }}/"
    dest: "{{ server_tmp_mnt }}"
    recursive: yes
    owner: yes
    group: yes
  delegate_to: "{{ server_hostname }}" 

- name: Unmount and remove temp mount {{ server_tmp_mnt }}
  mount:
    src: "{{ server_disk_dev }}1"
    path: "{{ server_tmp_mnt }}"
    state: absent
