---
#####################################################################################################################
# Configurations for Splunk server.conf
####################################################################################################################

splunk_server_conf:
  general:
    pass4SymmKey: "{{ vault_general_pass4SymmKey }}"
    site: site1
  sslConfig:
    sslPassword: "{{ vault_sslConfig_sslPassword }}"
  license:
    master_uri: dynamic
  clustering:
    mode: slave
    master_uri: dynamic
    pass4SymmKey: "{{ vault_clustering_pass4SymmKey }}"
    multisite: true
    cluster_label: "{{ target_env }}"
    replication_factor: 3
    search_factor: 2              
  replication_port_ssl:
    port: 9888
    rootCA: $SPLUNK_HOME/etc/auth/cacert.pem
    serverCert: $SPLUNK_HOME/etc/auth/server.pem
    password: "{{ vault_replication_port_sslPassword }}"
    disabled: false
  diskUsage:
    minFreeSpace: 1000
