---
#####################################################################################################################
# Restart shcmembers
#####################################################################################################################

- name: Run splunk restart
  command: "{{ splunk_installation.splunk_home_path }}/bin/splunk restart"
  when: splunk_server_conf.shclustering is defined and splunk_server_conf.shclustering.disabled == "false"
