---
#####################################################################################################################
# Configurations for Splunk distsearch.conf
#####################################################################################################################

#####################################################################################################################
# [distributedSearch]
#####################################################################################################################

- set_fact:
    splunk_mgm_list: []

- set_fact:
    splunk_mgm_list: "{{ splunk_mgm_list }} + ['https://{{ item }}:8089']"
  loop: "{{ query('inventory_hostnames', 'all:!pors_server:!monitoringconsole') }}"

- name: "Configure distsearch.conf [distributedSearch] - server state=present" 
  ini_file:
    dest: "{{ splunk_conf_path }}/distsearch.conf"
    section: distributedSearch
    option: servers
    value: "{{ splunk_mgm_list |join(',') }}"
    state: present
  notify: splunk restart
