---
- name: "Create Proxmox VM(s)"
  community.general.proxmox_kvm:
        proxmox_default_behavior: compatibility
        node: "{{ proxmox.node[px_var].name }}"
        api_user: "{{ proxmox.node[px_var].api_user }}"
        api_token_id: "{{ proxmox.node[px_var].api_token_id }}"
        api_token_secret: "{{ proxmox.node[px_var].api_token_secret }}"
        api_host: "{{ proxmox.node[px_var].api_host }}"
        clone: "{{ proxmox.node[px_var].ansible_template_name }}"
        name: "{{ item }}"
        description: "{{ server_notes }} on {{ datetime }}"
        storage: "{{ proxmox.node[px_var].storage }}"
        virtio: '{"virtio1":"{{ proxmox.node[px_var].storage }}:10"}'
        timeout: 120
  register: clone_output
  failed_when: clone_output.msg != (clone_output.msg | regex_search("VM {{ item }} with newid .* cloned from vm with vmid .*"))
  run_once: True
  loop: "{{ server_hostname }}"
  loop_control:
    pause: 15

- name: Giving PVE some time to actually finalize the VM...
  pause:
    seconds: 10
