---
- name: splunk actions
  hosts: "*"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  no_log: false 
  gather_facts: False

  handlers:
    - include: ../../roles/common/handlers/main.yml

  tasks:
    - name: "splunk {{ splunk_action }} (this can take some time before you see results here ...)"
      shell: echo
      notify: "splunk {{ splunk_action }}"
      register: actionresult

    - meta: flush_handlers
