---
- hosts: "{{ target }}"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root

  tasks:
   - name: reboot a remote system
     reboot:
        msg: "reboot initiated by Ansible Engine"
