---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [shclustering]
#####################################################################################################################

- name: "Configure server.conf [shclustering] - disabled state=present"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=shclustering
            option=disabled
            value={{ splunk_server_conf.shclustering.disabled }}
            state=present
  when:
    - splunk_server_conf.shclustering.disabled is defined
    - splunk_server_conf.shclustering.disabled == False
    - splunk_server_conf.shclustering.mode == "member"
  notify: splunk restart

- name: "Configure server.conf [shclustering] - disabled state=absent"
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=shclustering
            option=disabled
            state=absent
  when:
    - splunk_server_conf.shclustering.disabled is undefined
      or splunk_server_conf.shclustering.disabled != False
      or splunk_server_conf.shclustering.mode != "member"
  notify: splunk restart
