---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [clustering]
#####################################################################################################################

# mode

- name: "Configure server.conf [shclustering] - mode state=present"
  ini_file: dest="{{ splunk_conf_path }}/server.conf"
            section=shclustering
            option=mode
            value="{{ splunk_server_conf.shclustering.mode }}"
            state=present
  when: 
    - splunk_server_conf.shclustering.mode is defined
    - splunk_server_conf.shclustering.mode != "disabled"
  notify: splunk restart

- name: "Configure server.conf [shclustering] - mode state=absent (default)"
  ini_file: dest="{{ splunk_conf_path }}/server.conf"
            section=shclustering
            option=mode
            state=absent
  when: splunk_server_conf.shclustering.mode is undefined or
        splunk_server_conf.shclustering.mode == "disabled"
  notify: splunk restart

