---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

splunk_server_conf:
  general:
    pass4SymmKey: "{{ vault_general_pass4SymmKey }}"
  license:
    master_uri: dynamic
  sslConfig:
    sslPassword: "{{ vault_sslConfig_sslPassword }}"
