---
##################################################################
# Basic server system configuration
##################################################################

# misc
remote_system:
    local_gituser: ansible

# token based authentication for accessing git
tokenauth:
    gituser: ""
    gitpassword: ""

# NTP settings
ntp_enabled: true
ntp_timezone: Etc/UTC
ntp_manage_config: true
ntp_servers:
    - 0.de.pool.ntp.org iburst
    - 1.de.pool.ntp.org iburst
