- name: ELRepo - kernel-lt
  yum:
    name: "{{ system_yum.elrepo.kernel.name }}"
    enablerepo: "elrepo-kernel"
    update_cache: yes

- name: Enable kernel as default on boot
  shell: "grub2-set-default {{ system_yum.elrepo.kernel.setboot }}"
  when: 
    - ('ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"')
    - system_yum.elrepo.kernel.setboot is defined

- name: generate new grub conf
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg
  when:
    - system_yum.elrepo.kernel.setboot is defined
