---
#####################################################################################################################
# Configurations for Splunk inputs.conf
#####################################################################################################################

#####################################################################################################################
# [SSL]
#####################################################################################################################

# password

- name: "Configure inputs.conf [SSL] - set password"
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=SSL
            option=sslPassword
            value={{ splunk_inputs_conf.SSL.sslPassword }}
            state=present
  when: splunk_inputs_conf.SSL.sslPassword is defined
  notify: splunk restart

- name: "Configure inputs.conf [SSL] - unset password (default)"
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=SSL
            option=sslPassword
            state=absent
  when: splunk_inputs_conf.SSL.sslPassword is undefined
  notify: splunk restart
