---
- name: create {{ server_disk_dev }} ({{ server_disk_name }})
  google.cloud.gcp_compute_disk:
    auth_kind: "{{ googlecp.project[project_name].cred_kind }}"
    service_account_file: "{{ googlecp.project[project_name].cred_file }}"
    project: "{{ googlecp.project[project_name].id }}"
    zone: "{{ googlecp.project[project_name].zone }}"
    scopes: "{{ googlecp.project[project_name].scopes }}"
    name: "{{ server_shortname }}-{{ server_disk_name }}"
    size_gb: "{{ server_disk_sizegb }}"
    source_image: "{{ googlecp.project[project_name].source_image }}"
    type: "{{ server_disk_type }}"
    state: present
  register: computed_disk
  when: server_disk_sizegb is defined

- name: add disk(s) to the existing instance {{ server_shortname }}
  google.cloud.gcp_compute_instance:
    auth_kind: "{{ googlecp.project[project_name].cred_kind }}"
    service_account_file: "{{ googlecp.project[project_name].cred_file }}"
    project: "{{ googlecp.project[project_name].id }}"
    zone: "{{ googlecp.project[project_name].zone }}"
    scopes: "{{ googlecp.project[project_name].scopes }}"
    name: "{{ server_shortname }}"
    hostname: "{{ server_hostname }}"
    machine_type: "{{ server_machine_type }}"
    metadata:
        service: "{{ googlecp.project[project_name].metadata_service }}"
        landscape: "{{ googlecp.project[project_name].metadata_landscape }}"
        role: "{{ server_metadata_role }}"
    disks:
        - auto_delete: "{{ server_disk_persistence | default(true)}}"
          boot: "{{ server_disk_bootdev }}"
          source: "{{ computed_disk }}"
    state: present
    when: computed_disk is defined
