---
- name: create a instance
  google.cloud.gcp_compute_instance:
    auth_kind: "{{ googlecp.project[project_name].cred_kind }}"
    service_account_file: "{{ googlecp.project[project_name].cred_file }}"
    project: "{{ googlecp.project[project_name].id }}"
    zone: "{{ googlecp.project[project_name].zone }}"
    scopes: "{{ googlecp.project[project_name].scopes }}"
    name: "{{ server_shortname }}"
    hostname: "{{ server_hostname }}"
    machine_type: "{{ server_machine_type }}"
    metadata:
        service: "{{ googlecp.project[project_name].metadata_service }}"
        landscape: "{{ googlecp.project[project_name].metadata_landscape }}"
        role: "{{ server_metadata_role }}"
    network_interfaces:
        - subnetwork:
            selfLink: "https://www.googleapis.com/compute/v1/projects/{{ googlecp.project[project_name].id }}/regions/{{ googlecp.project[project_name].region }}/subnetworks/{{ googlecp.project[project_name].subnet }}"
          network_ip: "{{ server_ip }}"
    state: present
  register: instance
