---
- name: create root disk
  google.cloud.gcp_compute_disk:
    auth_kind: "{{ googlecp.project[project_name].cred_kind }}"
    service_account_file: "{{ googlecp.project[project_name].cred_file }}"
    project: "{{ googlecp.project[project_name].id }}"
    zone: "{{ googlecp.project[project_name].zone }}"
    scopes: "{{ googlecp.project[project_name].scopes }}"
    name: "{{ server_shortname }}-root"
    size_gb: "{{ server_disk_sizegb }}"
    source_image: "{{ googlecp.project[project_name].source_image }}"
    state: present
  register: root_disk
  when: server_disk_sizegb is defined

- name: create opt disk
  google.cloud.gcp_compute_disk:
    auth_kind: "{{ googlecp.project[project_name].cred_kind }}"
    service_account_file: "{{ googlecp.project[project_name].cred_file }}"
    project: "{{ googlecp.project[project_name].id }}"
    zone: "{{ googlecp.project[project_name].zone }}"
    scopes: "{{ googlecp.project[project_name].scopes }}"
    name: "{{ server_shortname }}-opt"
    size_gb: "{{ server_disk_sizegb_opt }}"
    type: "{{ disk_type_opt }}"
    state: present
  register: opt_disk
  when: gcp_configure_disk_opt is defined and server_disk_sizegb_opt is defined

- name: create tmp disk
  google.cloud.gcp_compute_disk:
    auth_kind: "{{ googlecp.project[project_name].cred_kind }}"
    service_account_file: "{{ googlecp.project[project_name].cred_file }}"
    project: "{{ googlecp.project[project_name].id }}"
    zone: "{{ googlecp.project[project_name].zone }}"
    scopes: "{{ googlecp.project[project_name].scopes }}"
    name: "{{ server_shortname }}-tmp"
    size_gb: "{{ server_disk_sizegb_tmp }}"
    type: "{{ disk_type_tmp }}"
    state: present
  register: tmp_disk
  when: gcp_configure_disk_tmp is defined server_disk_sizegb_tmp is defined

- name: create var disk
  google.cloud.gcp_compute_disk:
    auth_kind: "{{ googlecp.project[project_name].cred_kind }}"
    service_account_file: "{{ googlecp.project[project_name].cred_file }}"
    project: "{{ googlecp.project[project_name].id }}"
    zone: "{{ googlecp.project[project_name].zone }}"
    scopes: "{{ googlecp.project[project_name].scopes }}"
    name: "{{ server_shortname }}-var"
    size_gb: "{{ server_disk_sizegb_var }}"
    type: "{{ disk_type_var }}"
    state: present
  register: var_disk
  when: gcp_configure_disk_var is defined server_disk_sizegb_var is defined

- name: create swap disk
  google.cloud.gcp_compute_disk:
    auth_kind: "{{ googlecp.project[project_name].cred_kind }}"
    service_account_file: "{{ googlecp.project[project_name].cred_file }}"
    project: "{{ googlecp.project[project_name].id }}"
    zone: "{{ googlecp.project[project_name].zone }}"
    scopes: "{{ googlecp.project[project_name].scopes }}"
    name: "{{ server_shortname }}-swap"
    size_gb: "{{ server_disk_sizegb_swap }}"
    type: "{{ disk_type_swap }}"
    state: present
  register: swap_disk
  when: gcp_configure_disk_swap is defined and server_disk_sizegb_swap is defined
