---
- set_fact: datetime="{{lookup('pipe','date \"+%Y/%m/%d %H:%M\"')}}"
  run_once: True

- include_tasks: gcp_configure_address.yml
  when: gcp_configure_address is defined and gcp_configure_address != False

- include_tasks: gcp_create_instance.yml
  when: gcp_create_instance is defined and gcp_create_instance != False
