---
- name: "Deploy MonitoringConsole keys to: {{ target }}"
  hosts: "monitoringconsole"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: "{{ splunk_install_user }}"

  vars:
    parsed_groups: "{{ target }}"
    splunk_restart: False

  roles:
    - group/searchhead

- name: "Configure splunk Monitoring Console (Roles)"
  hosts: monitoringconsole
  connection: local

  roles:
    - group/monitoringconsole

  vars:
    splunk_restart: False
