---
# HINT: The "hosts" value here is a dynamic group name used in PORS

- name: Configure splunk indexers
  hosts: "{{ target }}"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: "{{ splunk_install_user }}"

  roles:
    - system_sshid
    - conf/web
    - conf/inputs
    - conf/server

  vars:
    splunk_restart: True

  # flush notify handlers to activate the splunk config
  post_tasks:
    - meta: flush_handlers

