---

# HINT: The "hosts" value here is a dynamic group name used in PORS
# and so not necessarily the exact group name within your hosts file!

- name: Configure splunk searchheads
  hosts: 
        - searchhead
        - activeinput
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: "{{ splunk_install_user }}"

  roles:
    - system_sshid
    - group/searchhead
    - conf/web
    - conf/outputs
    - conf/server
