- name: Configure splunk peernodes
  hosts: peernode
  remote_user: ansible
  become: yes
  become_user: "{{ splunk_install_user }}"

  roles:
    - system_sshid
    - conf/web
    - conf/inputs
    - conf/server
