- name: Upgrade Splunk
  hosts: "*:!repository"
  remote_user: ansible
  become: yes
  become_user: root
  strategy: free
  #do NOT use no_log: True here as it will be effective for all sub tasks then
  gather_facts: True

  vars:
    splunk_upgrade: True

#  vars_prompt:
#    - name: "splunk_user"
#      prompt: "\n\tsplunk> API account name (required for Indexer upgrades!)\n\tONLY leave this empty when you do NOT want to upgrade splunk on an indexer!! "
#      private: no
#    - name: "splunk_password"
#      prompt: "\n\tsplunk> API password (optional)\n\t(supports only these special chars for sure: -,_,%,@)"
#      private: yes

  roles:
    - splunk_info
    - install

- include: ae_install_shelper.yml
  when: shelper_installation.enabled
