- name: Upgrade Splunk
  hosts: "*:!pors_server"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  strategy: free
  #do NOT use no_log: True here as it will be effective for all sub tasks then
  gather_facts: True

  vars:
    splunk_upgrade: True

  roles:
    - splunk_info
    - install

- include: ../shelper/ae_install_shelper.yml
  when: shelper_installation.enabled
