---
- name: Upgrade System
  hosts: "*:!pors_server"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  strategy: free
  #do NOT use no_log: True here as it will be effective for all sub tasks then
  gather_facts: True

  tasks:
    - debug:
        var: splunk_with_system_upgrade

    - import_role:
        name: system_base
      when: splunk_with_system_upgrade is defined and splunk_with_system_upgrade == True

- name: Upgrade Splunk
  hosts: "*:!pors_server"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  strategy: free
  #do NOT use no_log: True here as it will be effective for all sub tasks then
  gather_facts: True

  vars:
    splunk_upgrade: True

  roles:
    - splunk_info
    - install

- include: ../shelper/ae_install_shelper.yml
  when: shelper_installation.enabled
