---
# HINT: The "hosts" value here is a dynamic group name used in PORS
# and so not necessarily the exact group name within your hosts file!

- name: "Configure splunk Monitoring Console (System)"
  hosts: monitoringconsole
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: "{{ splunk_install_user }}"

  roles:
    - system_sshid
    - conf/web
    - conf/outputs
    - conf/server
    - conf/distsearch

  vars:
    splunk_restart: True

  # flush notify handlers to activate the splunk config
  post_tasks:
    - meta: flush_handlers
