---
- name: "Configure splunk Monitoring Console (Roles)"
  hosts: monitoringconsole
  connection: local

  roles:
    - group/monitoringconsole

  vars:
    splunk_restart: True

  # flush notify handlers to activate the splunk config
  post_tasks:
    - meta: flush_handlers
