- name: Upgrade cribl logstream
  hosts: "*:!pors_server"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  strategy: free
  gather_facts: True
  #do NOT use "no_log: True" here as it will be effective for all sub tasks then

  vars:
    logstream_upgrade: True

  roles:
    - logstream_info
    - install_logstream

