---
#####################################################################################################################
# Configurations for Splunk deployment directory
# Keep in mind to replace "-" and "/" with an underscore "_"
#####################################################################################################################

deployment:
    # no direct push of apps to a SHC member! Use the Deployer to push.
    dir: disabled-apps
