---
#####################################################################################################################
# Configurations for Splunk distsearch.conf
####################################################################################################################

splunk_distsearch_conf:
  distributedSearch:
     servers: 
        - "{{ groups.peernode }}"
