---
- name: "splunk helper actions"
  hosts: "*"
  remote_user: "ansible"
  become: yes
  become_user: "{{ splunk_install_user }}"
  gather_facts: False

  handlers:
    - include: ../roles/shelper/handlers/main.yml

  tasks:
    - name: "shelper {{ shelper_action }} (this can take some time before you see results here ...)"
      debug:
        msg: "Please be patient! {{ shelper_action }} in progress"

    - name: "shelper {{ shelper_action }} (this can take some time before you see results here ...)"
      shell: echo 
      register: actionresult
      notify: "shelper {{ shelper_action }}"

    - meta: flush_handlers

    - name: Print result
      debug: 
        msg: "{{ shelper_result.stdout_lines }}"
