---
- name: clear history root
  become: yes
  become_user: root
  command: rm /root/.bash_history

- name: clear history splunk
  command: rm ~/.bash_history
  become: yes
  become_user: "{{ splunk_install_user }}"

