---
#####################################################################################################################
# Copy Enterprise License Keys
#####################################################################################################################

- name: Install splunk license(s)
  copy:
    src: "{{ splunk_repository.repository_root }}/licenses/enterprise/"
    dest: "{{ splunk_installation.splunk_home_path }}/etc/licenses/enterprise/"
    mode: u+rwx,g+rwx
    owner: "{{ splunk_install_user }}"
    group: "{{ splunk_install_user }}"
