---
- name: (Re-)configure a Proxmox VM
  hosts: "pors_server"
  gather_facts: false
  connection: local

  vars:
    ansible_python_interpreter: /usr/bin/python3
    kvm_create: false
    kvm_configure: true
    kvm_poweron: false

  roles:
        - proxmox
