---

- debug: msg="{{ vars['ansible_virtualization_type'] }}"

- name: check vm
  yum: 
    list: open-vm-tools
  register: vmtools

- name: "YEAH"
  debug: msg="{{ item.version }} {{ item.yumstate }}"
  with_items: "{{ vmtools.results }}"
  when: item.yumstate == "installed"
  register: moo

- name: "moooooo"
  shell: echo "same version installed"
  when: vmtools.results
        | selectattr("yumstate", "match", "installed")
        | selectattr("version", "match", vmtools_packages.linux_64_rpm.tools.version )
        | selectattr("release", "match", "4.el7_3")
        | list |length != 0
