---
- name: Deploy Google Cloud instance(s)
  hosts: "pors_server"
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3
    gcp_configure_address: True
    gcp_create_instance: True

  roles:
    - googlecp 
