---
- include: update.yml
  when: 
    - system_yum.upgrade_system is defined and system_yum.upgrade_system == True
    - ansible_facts['os_family'] == "RedHat"

- include: add_elrepo.yml
  when: system_yum.elrepo.enabled and ansible_facts['os_family'] == "RedHat"

- include: install_elrepo_kernel.yml
  when: 'system_yum.elrepo.kernel.setup == "yes"' and ansible_facts['os_family'] == "RedHat"
