---
- name: Start Splunk (non-systemd only)
  service: name=splunk
           state=started
#  when: splunkversionnum < 72

#- name: Start Splunk (>= v7.2)
#  systemd: name=Splunkd
#           state=started
#  when: splunkversionnum >= 72

