---
- name: Stop Splunk (non-systemd only)
  service: name=splunk
           state=stopped
#  when: splunkversionnum < 72

#- name: Stop Splunk (>= 7.2)
#  service: name=Splunkd
#           state=stopped
#  when: splunkversionnum >= 72
#
