---
- name: First Time Boot Splunk (non-systemd only)
  service: name=splunk
           state=started
#  when: splunkversionnum < 72

- name: Stop Splunk (non-systemd only)
  service: name=splunk
           state=stopped
#  when: splunkversionnum < 72

#- name: First Time Boot Splunk (= v7.2)
#  service: name=Splunkd
#           state=started
#  when: splunkversionnum == 72

#- name: Stop Splunk (= 7.2)
#  service: name=Splunkd
#           state=stopped
#  when: splunkversionnum == 72

